task8.3 added
Degiv/spbsu_homework pull request #23
Opened 2017-11-24 13:45 UTC by Degiv

2017-12-11 08:02 UTC, jzuken requested changes

2017-12-11 08:02 UTC, jzuken commented on Homework_8/task8.3/hashtable.cpp
> +    return (double)table.usedCounter / (double)table.size;
достаточно только первый к даблу привести. и обычно после скобок пробелы ставят

2017-12-11 08:02 UTC, jzuken commented on Homework_8/task8.3/list.cpp
> +    else
а зачем тут else?

2017-12-11 08:02 UTC, jzuken commented on Homework_8/task8.3/list.cpp
> +        pop(list);
а кто эти строки удалит?

2017-12-11 08:02 UTC, jzuken commented on Homework_8/task8.3/list.cpp
> +bool add(List &list, String newValue)
лучше передавать сложные структуры данных по константной ссылке, если ты их менять не собираешься

2017-12-11 08:02 UTC, jzuken commented on Homework_8/task8.3/list.cpp
> +        newElement->value = clone(newValue);
опять же, а newValue кто удалит?

2017-12-15 19:03 UTC, Degiv commented on Homework_8/task8.3/list.cpp
> +bool add(List &list, String newValue)
Не понимаю о чем вы, мне же нужно менять поля листа

2017-12-16 14:00 UTC, jzuken commented on Homework_8/task8.3/list.cpp
> +bool add(List &list, String newValue)
ну прямо тут может и нужно, а вот в show() точно нет

2017-12-22 11:47 UTC, jzuken requested changes

2017-12-22 11:47 UTC, jzuken commented on Homework_8/task8.3/list.cpp
> +void show(List &list)
константных ссылок так и не вижу почему-то

2017-12-22 11:47 UTC, jzuken commented on Homework_8/task8.3/main.cpp
> +        input(curWord, fin);
память так и не почистил нормально. проверь аккуратно, пожалуйста, что все строки, которые ты в таблицу добавляешь, нормально удаляются

2017-12-23 18:25 UTC, Degiv commented on Homework_8/task8.3/main.cpp
> +        input(curWord, fin);
подскажите, пожалуйста, где остается память, я несколько раз все просмотрел, но не вижу...

2017-12-23 18:31 UTC, Degiv commented on Homework_8/task8.3/main.cpp
> +        input(curWord, fin);
а все, до меня дошло

2017-12-24 08:45 UTC, jzuken commented on Homework_8/task8.3/main.cpp
> +        input(curWord, fin);
а не надо смотреть, надо отлаживаться. 
например, проверить, что на каждый new вызывается правильный delete. как крайняя мера -- просто поставить отладочный вывод рядом с каждым new и delete и посмотреть, что будет

2017-12-28 13:01 UTC, jzuken commented
не помогло. посмотри на update() в таблице

2018-01-09 16:35 UTC, jzuken commented
всё ещё не помогло

2018-01-10 23:33 UTC, Degiv commented on Homework_8/task8.3/member.txt
> +
Я попробовал для update() выписать все new и отследить где они удаляются, у меня все сошлось. Посмотрите, пожалуйста, файл member.txt, я в нем где-то не прав?

2018-01-11 10:12 UTC, jzuken commented on Homework_8/task8.3/member.txt
> +
кодировка utf8 для слабых, да

2018-01-11 10:23 UTC, jzuken commented
ну если я скажу, что не так в этом файле, это не сильно будет отличаться от того, если я просто в код ткну, в members.txt та же ошибка. посмотри *внимательно* на update(), ошибка очень простая и довольно очевидная, если просто прочитать код

2018-01-11 11:50 UTC, Degiv commented on Homework_8/task8.3/member.txt
> +
можете, пожалуйста, ткнуть в код, я смотрю внимательно на update() и все хорошо, может я не  так понимаю что-то про память (

2018-01-11 11:55 UTC, Degiv commented
можете, пожалуйста, ткнуть в код, я смотрю внимательно на update() и все хорошо, может я не так понимаю что-то про память (

2018-01-11 13:37 UTC, merged